application:
  env: development
  server:
    host: 0.0.0.0
    port: 8080
  resources:
    database:
      write-service:
        driver: postgres
        instance: postgres
        port: 5432
        dbname: postgres
        username: postgres
        password: password
        options: sslmode=disable&TimeZone=UTC
